import { redirect } from "next/navigation";
import { getSql } from "@/lib/db/client";
import ReportGate from "./ReportGate";
import GatedReportFlow from "./GatedReportFlow";
import ReportView from "./ReportView";
import NarrativeReportView from "./NarrativeReportView";
import ScrollTracker from "./ScrollTracker";
import SiteFooter from "@/app/components/SiteFooter";
import type { AxisResult } from "@/lib/engine/scorer";
import { fetchPublishedNarrativeReport } from "@/lib/report/fetch-narrative";
import { resolveChildPronoun } from "@/lib/report/pronouns";
import type { Gender } from "@/lib/report/pronouns";

type Params = Promise<{ sessionId: string }>;
type SearchParams = Promise<{ f?: string }>;

export default async function ReportPage({
  params,
  searchParams,
}: {
  params: Params;
  searchParams: SearchParams;
}) {
  const { sessionId } = await params;
  const { f } = await searchParams;
  const fallbackMode = f === "1"; // set by generating page on hard-cap timeout — skip redirect

  // Validate UUID format before hitting the DB
  const UUID_RE =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!UUID_RE.test(sessionId)) {
    return <NotFound />;
  }

  const sql = getSql();
  const rows = (await sql`
    SELECT
      a.id,
      a.session_id,
      a.child_name,
      a.age_band,
      a.child_gender,
      a.archetype,
      a.parent_pattern,
      a.axes,
      a.weakest_two,
      a.parent_name,
      a.email,
      a.phone,
      a.concerns,
      a.tried,
      a.better,
      a.pricing_variant
    FROM assessments a
    WHERE a.session_id = ${sessionId}::uuid
    LIMIT 1
  `) as unknown as {
    id: string;
    session_id: string;
    child_name: string | null;
    age_band: string;
    child_gender: string | null;
    archetype: string;
    parent_pattern: string;
    axes: {
      stability: AxisResult;
      resistance: AxisResult;
      recovery: AxisResult;
    };
    weakest_two: string[];
    parent_name: string | null;
    email: string | null;
    phone: string | null;
    concerns: string[];
    tried: string[] | null;
    better: string[] | null;
    pricing_variant: string | null;
  }[];

  if (rows.length === 0) {
    return <NotFound />;
  }

  const row = rows[0];

  const gatedEnabled = process.env.NEXT_PUBLIC_GATED_REPORT_ENABLED === "true";
  const isGated = row.pricing_variant === "gated" && gatedEnabled;

  if (isGated) {
    const paidRows = (await sql`
      SELECT id FROM purchases
      WHERE assessment_id = ${row.id}::uuid AND status = 'paid'
      LIMIT 1
    `) as unknown as { id: string }[];

    if (paidRows.length === 0) {
      // Not yet paid — show the 3-screen gated flow
      const nrForTeaser = await fetchPublishedNarrativeReport(sql, row.id);
      const teaserMoment = (nrForTeaser?.narrative_moments ?? []).find(
        (m) => m.moment_id === "m_teaser",
      ) ?? null;
      return (
        <GatedReportFlow
          sessionId={sessionId}
          hasPhone={!!row.phone}
          initialPhone={row.phone ?? ""}
          teaserText={teaserMoment?.content ?? null}
          childName={row.child_name || "your child"}
        />
      );
    }
    // Paid — fall through to full report rendering below (parent_name gate skipped)
  } else {
    // Control arm (or pre-migration session with no variant): existing parent_name gate
    if (!row.parent_name) {
      await sql`
        INSERT INTO funnel_events (event_type, session_id, metadata)
        VALUES ('report_gate_view', ${sessionId}::uuid, '{}'::jsonb)
      `.catch((e: unknown) => console.warn("[funnel] report_gate_view:", (e as Error).message));

      return (
        <>
          <ReportGate sessionId={sessionId} />
          <SiteFooter />
        </>
      );
    }
  }

  // Check for a published narrative report (generated by /api/report/generate).
  // fetchPublishedNarrativeReport gates on status='published' AND superseded_by IS NULL —
  // draft reports are invisible here until explicitly promoted by an admin.
  const nr = await fetchPublishedNarrativeReport(sql, row.id);

  if (nr === null && !fallbackMode) {
    // No published narrative yet. Check whether generation is still in progress:
    // if no report row exists at all, the pipeline hasn't committed anything yet — redirect
    // to the animated waiting screen so the parent isn't silently dropped on the static fallback.
    // If a report row exists (draft, quality-failed, superseded) generation is done but blocked;
    // in that case the static fallback is the correct experience.
    const anyReport = (await sql`
      SELECT id FROM reports
      WHERE assessment_id = ${row.id}::uuid
      LIMIT 1
    `) as unknown as { id: string }[];

    if (anyReport.length === 0) {
      redirect(
        `/report/generating/${sessionId}?name=${encodeURIComponent(row.child_name ?? "")}&archetype=${encodeURIComponent(row.archetype ?? "")}`,
      );
    }
  }

  if (nr !== null) {
    await sql`
      INSERT INTO funnel_events (event_type, session_id, metadata)
      VALUES ('report_view', ${sessionId}::uuid, ${JSON.stringify({ archetype: row.archetype })}::jsonb)
    `.catch((e: unknown) => console.warn("[funnel] report_view:", (e as Error).message));

    const gender = (row.child_gender ?? null) as Gender;
    const pronouns = {
      subj:      resolveChildPronoun(gender, "subj"),
      obj:       resolveChildPronoun(gender, "obj"),
      poss:      resolveChildPronoun(gender, "poss"),
      reflexive: resolveChildPronoun(gender, "reflexive"),
    };
    return (
      <>
        <ScrollTracker sessionId={sessionId} />
        <NarrativeReportView
          moments={nr.narrative_moments}
          archetype={nr.archetype}
          archetypeFitTier={nr.archetype_fit_tier ?? "primary"}
          parentInstinct={nr.parent_instinct}
          familyLoop={nr.family_attention_loop}
          childName={row.child_name || "your child"}
          parentName={row.parent_name ?? "you"}
          email={row.email ?? ""}
          phone={row.phone ?? ""}
          concerns={row.concerns ?? []}
          sessionId={sessionId}
          pronouns={pronouns}
        />
      </>
    );
  }

  return (
    <>
      <ScrollTracker sessionId={sessionId} />
      <ReportView
        assessment={{
          ...row,
          parent_name: row.parent_name ?? "you",
        }}
      />
      <SiteFooter />
    </>
  );
}

function NotFound() {
  return (
    <main
      className="min-h-screen flex items-center justify-center p-6"
      style={{ background: "var(--paper)" }}
    >
      <div style={{ textAlign: "center" }}>
        <p
          className="text-lg font-semibold mb-2"
          style={{ color: "var(--ink)" }}
        >
          Report not found
        </p>
        <p className="text-sm" style={{ color: "var(--ink-dim)" }}>
          This link may have expired or the session was not saved correctly.
        </p>
      </div>
    </main>
  );
}
