// AUTO-GENERATED by scripts/gen-snapshot-distribution.mts — do not edit by hand.
// Re-run against production before every deploy that ships §2.
//
// Generated:      2026-09-19
// Source:         production (ep-green-truth-aqxygaj2), non-internal sessions only
// Total sessions: 337
//
// Counts are per dimension value. Values absent here (e.g. boredom-avoidance)
// have zero production sessions as of the generation date above.

export const SNAPSHOT_DISTRIBUTION: Record<string, Record<string, number>> = {
  attention_shape: { "narrow-deep": 178, "sensation-seeking": 71, "wide-shifting": 69, "social-anchored": 19 },
  attention_competition: { "internal": 133, "novelty": 96, "external": 92, "social": 10, "genuine-interest": 5, "task-escape": 1 },
  friction_response: { "solo-push": 97, "avoid": 87, "support-seek": 82, "emotional-derail": 59, "energized": 12 },
  recharge_type: { "autonomous-unstructured": 103, "cognitive-displacement": 97, "social-connection": 70, "sensory-quiet": 67 },
};

export const SNAPSHOT_DISTRIBUTION_TOTAL = 337;
export const SNAPSHOT_DISTRIBUTION_GENERATED = "2026-09-19";
