// Report v2 content generator. Deterministic parts (goal, evidence, headline, archetype
// card) are assembled from stored data; the free-text parts are generated by the LLM on the
// existing writing-engine path, validated, retried once with the errors fed back, then fall
// back to static archetype × worry copy. Default report stays v1; this only runs for ?report=v2.
import Anthropic from "@anthropic-ai/sdk";
import { WRITING_ENGINE_SYSTEM_PROMPT } from "@/lib/narrative/system-prompt";
import { QUESTIONS_BY_ID, ALL_QUESTIONS } from "@/lib/engine/questions";
import { displayChildName, type Gender } from "@/lib/report/pronouns";
import {
  canonicalConcern, goalForConcern, headlineForConcern, worryLabelFor, GOLD_LINE,
} from "./goal-mapping";
import {
  selectEvidence, rankDimensions, type AnsweredQuestion, type DimScore,
} from "./evidence";
import { validateGenerated } from "./validator";
import { composeFallback, archetypeDesc } from "@/content/report-v2/fallbacks";
import type { ReportV2Content, ReportV2Generated } from "./types";

const MODEL = "claude-sonnet-4-6";

let _client: Anthropic | null = null;
function getClient(): Anthropic {
  if (!_client) {
    if (!process.env.ANTHROPIC_API_KEY) throw new Error("ANTHROPIC_API_KEY is not set");
    _client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return _client;
}

export type AssessmentInput = {
  childName: string | null;
  childGender: string | null;
  archetype: string | null;
  concerns: string[] | null;
  answers: Record<string, string>;
  dimensions: Record<string, { value: string; winning_votes: number; data_points: number }>;
  goalText?: string | null;   // parent override via /api/report/goal, if any
  goalSource?: string | null;
};

// Build the ordered list of answered questions (verbatim option labels + dimension),
// in canonical question order — the input to deterministic evidence selection.
export function answeredFromAssessment(a: AssessmentInput): AnsweredQuestion[] {
  const out: AnsweredQuestion[] = [];
  for (const q of ALL_QUESTIONS) {
    const val = a.answers[q.id];
    if (val === undefined) continue;
    const opt = q.options.find((o) => o.value === val);
    if (!opt) continue;
    out.push({ id: q.id, dimension: q.dimension, label: opt.label });
  }
  return out;
}

function dimScores(a: AssessmentInput): DimScore[] {
  return Object.entries(a.dimensions ?? {}).map(([dimension, d]) => ({
    dimension,
    winning_votes: d?.winning_votes ?? 0,
  }));
}

function buildPrompt(a: AssessmentInput, ctx: {
  name: string; gender: Gender; concern: string; worryLabel: string;
  headline: string; goal: string; evidenceQuotes: string[]; archetype: string; archetypeDesc: string;
  priorErrors?: string[];
}): string {
  const them = ctx.name;
  const retry = ctx.priorErrors?.length
    ? `\n\nYour previous attempt FAILED these checks. Fix every one:\n- ${ctx.priorErrors.join("\n- ")}\n`
    : "";
  return `You are writing a short attention report for a parent of a child called ${them}.

What the parent told us they worry about most: ${ctx.worryLabel}.
The child's attention pattern (archetype): ${ctx.archetype} — ${ctx.archetypeDesc}
The goal we are working toward: "${ctx.goal}"
Three of the parent's OWN answers that pointed to this pattern:
${ctx.evidenceQuotes.map((q, i) => `${i + 1}. "${q}"`).join("\n")}

Write JSON ONLY, no prose around it, with exactly these keys:
{
  "shortGood": "one line — a real strength of ${them}, framed as capability",
  "shortWhy": "one line — why the ${ctx.worryLabel} happens, as a mechanism, never as blame",
  "shortFix": "one line — the single change that helps",
  "whyParas": ["two short sentences", "two short sentences"],
  "switch": { "instead": "the old move, under 8 words", "try": "the new move, under 8 words", "after": "one line on what changes when they try it" },
  "tonight": ["step 1", "step 2", "step 3"]
}

Hard rules (output is rejected otherwise):
- Plain, warm, specific. Reading age ~11. Every sentence 20 words or fewer.
- Never blame the parent. No "you've been", "your mistake", "you always".
- No clinical claims. Never the words diagnose, ADHD, or disorder.
- No hedging words: may, might, could, "can't promise".
- No invented statistics, numbers, or testimonials.
- Use the name ${them} naturally. Keep each field short enough for a phone card.
- shortGood, shortWhy, shortFix: 90 characters or fewer each.
- switch.instead and switch.try: 60 characters or fewer each.${retry}`;
}

function parseJson(text: string): ReportV2Generated {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const raw = fenced ? fenced[1] : text;
  const start = raw.indexOf("{");
  const end = raw.lastIndexOf("}");
  const obj = JSON.parse(raw.slice(start, end + 1));
  return {
    shortGood: String(obj.shortGood ?? ""),
    shortWhy: String(obj.shortWhy ?? ""),
    shortFix: String(obj.shortFix ?? ""),
    whyParas: [String(obj.whyParas?.[0] ?? ""), String(obj.whyParas?.[1] ?? "")],
    switch: {
      instead: String(obj.switch?.instead ?? ""),
      try: String(obj.switch?.try ?? ""),
      after: String(obj.switch?.after ?? ""),
    },
    tonight: [
      String(obj.tonight?.[0] ?? ""),
      String(obj.tonight?.[1] ?? ""),
      String(obj.tonight?.[2] ?? ""),
    ],
  };
}

async function callLLM(prompt: string): Promise<ReportV2Generated> {
  const res = await getClient().messages.create({
    model: MODEL,
    max_tokens: 1024,
    system: WRITING_ENGINE_SYSTEM_PROMPT,
    messages: [{ role: "user", content: prompt }],
  });
  const text = res.content.map((b) => (b.type === "text" ? b.text : "")).join("");
  return parseJson(text);
}

export type GenerateResult = { content: ReportV2Content; attempts: number };

export async function generateReportV2(a: AssessmentInput): Promise<GenerateResult> {
  const gender = (a.childGender ?? null) as Gender;
  const name = a.childName?.trim() ? displayChildName(a.childName) : "your child";
  const concern = canonicalConcern(a.concerns?.[0]);
  const worryLabel = worryLabelFor(concern);
  const archetype = a.archetype ?? "The All-In Kid";
  const archDesc = archetypeDesc(archetype, a.childName ?? "", gender);
  const headline = headlineForConcern(concern, a.childName ?? "", gender);
  // Parent override wins; otherwise the concern→goal mapping.
  const goal = a.goalText?.trim() ? a.goalText.trim() : goalForConcern(concern, a.childName ?? "", gender);

  const answered = answeredFromAssessment(a);
  const evidence = selectEvidence(answered, rankDimensions(dimScores(a)), a.childName ?? "", gender);
  const evidenceTie = `Put together, these three answers are what pointed us to ${name}’s pattern.`;
  const disclaimer =
    "Attention Architect is an educational tool for parents. It is not a medical or clinical assessment, and not a substitute for professional advice.";

  const ctx = {
    name, gender, concern, worryLabel, headline, goal,
    evidenceQuotes: evidence.map((e) => e.quote), archetype, archetypeDesc: archDesc,
  };

  let generated: ReportV2Generated | null = null;
  let source: "llm" | "fallback" = "fallback";
  let attempts = 0;
  let priorErrors: string[] | undefined;

  for (let i = 0; i < 2; i++) {
    attempts++;
    try {
      const g = await callLLM(buildPrompt(a, { ...ctx, priorErrors }));
      const v = validateGenerated(g);
      if (v.ok) { generated = g; source = "llm"; break; }
      priorErrors = v.errors;
    } catch (e) {
      priorErrors = [(e as Error).message];
      // On a hard error (no key / API down) there is no point retrying — fall back now.
      break;
    }
  }

  if (!generated) {
    generated = composeFallback(archetype, concern, a.childName ?? "", gender);
    source = "fallback";
  }

  const content: ReportV2Content = {
    ...generated,
    source,
    childName: name,
    concern,
    worryLabel,
    headline,
    goldLine: GOLD_LINE,
    goal,
    evidence,
    evidenceTie,
    archetype,
    archetypeDesc: archDesc,
    disclaimer,
  };
  return { content, attempts };
}
