import { neon } from "@neondatabase/serverless";
const sql = neon(process.env.DATABASE_URL_PROD!);
const rows = await sql`SELECT axes, weakest_two, archetype FROM assessments WHERE session_id = '4dce903e-dc17-44d6-9765-9fc713b851f8'::uuid`;
const a = rows[0] as { axes: Record<string, {value:number;norm:number;band:string;eligible?:boolean}>; weakest_two: string[]; archetype: string };
const ax = a.axes;
console.log("archetype:", a.archetype);
console.log("weakest_two:", JSON.stringify(a.weakest_two));
console.log("attention: ", `value=${ax.attention?.value?.toFixed(4)} norm=${ax.attention?.norm?.toFixed(4)} band=${ax.attention?.band}`);
console.log("stability: ", `value=${ax.stability?.value?.toFixed(4)} norm=${ax.stability?.norm?.toFixed(4)} band=${ax.stability?.band}`);
console.log("resistance:", `value=${ax.resistance?.value?.toFixed(4)} norm=${ax.resistance?.norm?.toFixed(4)} band=${ax.resistance?.band}`);
console.log("recovery:  ", `value=${ax.recovery?.value?.toFixed(4)} norm=${ax.recovery?.norm?.toFixed(4)} band=${ax.recovery?.band} eligible=${ax.recovery?.eligible}`);
