// Deploy-time generator for lib/report/snapshot-distribution.ts — the build-time
// constant that powers §2 rarity tags and proportion bars. Same discipline as a
// migration: run this against production before deploy so the shipped counts are
// fresh, and the generated file records WHEN it was built and from how many
// sessions (a stale constant with no timestamp is worse than a live query).
//
//   npx tsx scripts/gen-snapshot-distribution.mts
//
// Reads DATABASE_URL_PROD from .env.local and refuses to run against anything
// that is not the ep-green-truth-aqxygaj2 production endpoint. Counts EXCLUDE
// internal sessions.

import { neon } from "@neondatabase/serverless";
import { readFileSync, writeFileSync } from "node:fs";

const envText = readFileSync(".env.local", "utf8");
const line = envText.split("\n").find(l => l.startsWith("DATABASE_URL_PROD="));
if (!line) throw new Error("DATABASE_URL_PROD not found in .env.local");
const url = line.slice("DATABASE_URL_PROD=".length).trim().replace(/^["']|["']$/g, "");
if (!url.includes("ep-green-truth-aqxygaj2")) {
  throw new Error("Refusing to run: not the ep-green-truth-aqxygaj2 production endpoint");
}

const sql = neon(url);
const DIMS = ["attention_shape", "attention_competition", "friction_response", "recharge_type"];

const total = (await sql`SELECT count(*)::int n FROM assessments WHERE is_internal = false`)[0].n as number;

const dist: Record<string, Record<string, number>> = {};
for (const dim of DIMS) {
  const rows = await sql`
    SELECT a.dimensions->${dim}->>'value' AS val, count(*)::int AS n
    FROM assessments a
    WHERE a.is_internal = false AND a.dimensions->${dim}->>'value' IS NOT NULL
    GROUP BY 1 ORDER BY n DESC, val ASC
  `;
  dist[dim] = {};
  for (const r of rows as { val: string; n: number }[]) dist[dim][r.val] = r.n;
}

// YYYY-MM-DD in UTC — a plain node script, so Date is available here.
const genDate = new Date().toISOString().slice(0, 10);

const j = (s: unknown) => JSON.stringify(s);
const body = `// AUTO-GENERATED by scripts/gen-snapshot-distribution.mts — do not edit by hand.
// Re-run against production before every deploy that ships §2.
//
// Generated:      ${genDate}
// Source:         production (ep-green-truth-aqxygaj2), non-internal sessions only
// Total sessions: ${total}
//
// Counts are per dimension value. Values absent here (e.g. boredom-avoidance)
// have zero production sessions as of the generation date above.

export const SNAPSHOT_DISTRIBUTION: Record<string, Record<string, number>> = {
${DIMS.map(d => `  ${d}: { ${Object.entries(dist[d]).map(([v, n]) => `${j(v)}: ${n}`).join(", ")} },`).join("\n")}
};

export const SNAPSHOT_DISTRIBUTION_TOTAL = ${total};
export const SNAPSHOT_DISTRIBUTION_GENERATED = ${j(genDate)};
`;

writeFileSync("lib/report/snapshot-distribution.ts", body);
console.log(`Wrote lib/report/snapshot-distribution.ts — generated ${genDate}, total ${total}.`);
for (const d of DIMS) console.log(`  ${d}: ${JSON.stringify(dist[d])}`);
